version: '3.2'
services:
  web:
    build: ./web
    links:
      - api:api
    ports:
       - 8080:8080
    environment:
      SERVER_PORT: 8080
    volumes:
      - ./web/Docker:/app
  api:
    build: ./api
    volumes:
      - ./api/app/Docker:/app
      - ./api/app/csvs:/csvs
    ports:
      - 5000:5000
