# Generated by Django 3.2.13 on 2022-04-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coins',
            name='coin_name',
            field=models.CharField(max_length=255, verbose_name='Coin name'),
        ),
    ]
