# Generated by Django 3.2.13 on 2022-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20220429_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
