# Generated by Django 3.2.13 on 2022-05-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_test_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_model',
            name='text',
            field=models.TextField(default=0, verbose_name='Text: '),
            preserve_default=False,
        ),
    ]
