# Generated by Django 3.2.13 on 2022-05-15 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_test_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
    ]
