# Generated by Django 3.2.13 on 2022-05-15 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_coins_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coins',
            name='date',
            field=models.DateField(verbose_name='Date '),
        ),
    ]
