# Generated by Django 4.1 on 2022-12-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255, verbose_name='Coin name')),
                ('price', models.FloatField(verbose_name='Price')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date ')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
            ],
        ),
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text: ')),
                ('name', models.CharField(max_length=50, verbose_name="What's your name? ")),
            ],
            options={
                'verbose_name': 'test_model',
                'verbose_name_plural': 'test_models',
            },
        ),
    ]
