# Generated by Django 3.2.13 on 2022-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_test_model_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_model',
            name='name',
            field=models.CharField(default=10, max_length=50, verbose_name="What's your name? "),
            preserve_default=False,
        ),
    ]
