# Generated by Django 3.2.13 on 2022-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20220515_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date '),
        ),
        migrations.AlterField(
            model_name='coins',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
